import pygame
pygame.init()
NIVEL_INICIAL = "level1"
ENEMY_TYPE1 = "TYPE_1"
ENEMY_TYPE2 = "TYPE_2"
ENEMY_TYPE3 = "TYPE_3"
ENEMY_TYPE4 = "TYPE_4"
ENEMY_TYPE5 = "TYPE_5"
ENEMY_TYPE6 = "TYPE_6"
ENEMY_TYPE7 = "TYPE_7"
ENEMY_TYPE8 = "TYPE_8"
ENEMY_TYPE9 = "TYPE_9"
ENEMY_TYPE10 = "TYPE_10"
ENEMY_TYPE11 = "TYPE_11"
ENEMY_TYPE12 = "TYPE_12"
OBJECT_TYPE1 = "TYPE_1"
OBJECT_TYPE2 = "TYPE_2"
OBJECT_TYPE3 = "TYPE_3"
OBJECT_TYPE4 = "TYPE_4"
OBJECT_TYPE5 = "TYPE_5"
OBJECT_TYPE6 = "TYPE_6"
OBJECT_TYPE7 = "TYPE_7"
TEXT_FONT = pygame.font.Font("assets/font.otf", 32)
TEXT_FONT2 = pygame.font.Font("assets/font.otf", 100)
